apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sjekk-adressebeskyttelse
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 5
    path: /isalive
  readiness:
    initialDelay: 5
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: sjekkadressebeskyttelse
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
    - name: PDL_URL
      value: "https://etterlatte-proxy.dev-fss-pub.nais.io/pdl"
  accessPolicy:
    outbound:
      external:
        - host: "https://etterlatte-proxy.dev-fss-pub.nais.io"
