apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: selvbetjening-ui
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  ingresses:
    - "https://etterlatte-selvbetjening-ui.dev.nav.no"
    - "https://etterlatteytelser.dev.nav.no"
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  webproxy: true
  tokenx:
    enabled: true
    idporten:
      enabled: true
      redirectURI: "/oauth2/callback"
      frontchannelLogoutURI: "/oauth2/logout"
  envFrom:
    - secret: redis-password
    - secret: session-encrypt-key
  env:
    - name: API_URL
      value: http://selvbetjening-api
    - name: NODE_ENV
      value: dev
    - name: REDIS_HOST
      value: selvbetjening-redis.etterlatte.svc.cluster.local
  accessPolicy:
    outbound:
      external:
        - host: loginservice.dev.nav.no
        - host: dekoratoren.dev.nav.no
        - host: tokendings.dev-gcp.nais.io
      rules:
        - application: selvbetjening-api
        - application: selvbetjening-redis