apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: selvbetjening-api
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "internal/isalive"
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "internal/isready"
    initialDelay: 20
    timeout: 1
  replicas:
    min: 1
    max: 1
  tokenx:
    enabled: true
  ingresses:
    - "https://etterlatte-selvbetjening-api.dev.adeo.no"
  accessPolicy:
    inbound:
      rules:
        - application: selvbetjening-ui