apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bpc-exporer
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "isalive"
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "isready"
    initialDelay: 20
    timeout: 1
  replicas:
    min: 1
    max: 1
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
  kafka:
    pool: nav-dev