apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bpc-exporer
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://etterlatte-bpc-explorer.dev.intern.nav.no"
  liveness:
    path: "internal/isalive"
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "internal/isready"
    initialDelay: 20
    timeout: 1
  replicas:
    min: 1
    max: 1
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://etterlatte-bpc-explorer.dev.intern.nav.no/login/oauth2/code/"
      claims:
        groups:
          - id: 650684ff-8107-4ae4-98fc-e18b5cf3188b
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
  kafka:
    pool: nav-dev