apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: finn-etterlatte
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 5
    path: /isalive
  readiness:
    initialDelay: 5
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: finnetterlatte
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
    - name: PDL_URL
      value: "https://pdl-api.dev.adeo.no/graphql"
    - name: STS_URL
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/token?grant_type=client_credentials&scope=openid"
  envFrom:
    - secret: barnepensjon-secrets
  accessPolicy:
    outbound:
      external:
        - host: "pdl-api.dev.adeo.no"
        - host: "security-token-service.nais.preprod.local"
