name: Deploy alerts to NAIS
on:
  workflow_dispatch: # Allow manually triggered workflow run
  push:
    branches:
      - main
    paths:
      - 'apps/*/.nais/alerts.yaml'
      - '.github/workflows/alerts.yaml'
jobs:
  deploy-alerts:
    name: Deploy alert changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [barnepensjon-ui, gjenlevendepensjon-ui, selvbetjening-api, innsendt-soeknad, sjekk-adressebeskyttelse, journalfoer-soeknad]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/${{ matrix.app }}/.nais/alerts.yaml
          VAR: SLACK_ALERTS_CHANNEL=#team-etterlatte-alarm,LOGS_URL=https://logs.adeo.no/goto/e3cd5dc0-39ee-11ed-b3e8-d969437dd878

      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: apps/${{ matrix.app }}/.nais/alerts.yaml
          VAR: SLACK_ALERTS_CHANNEL=#team-etterlatte-alarm,LOGS_URL=https://logs.adeo.no/goto/25018180-3a4a-11ed-b3e8-d969437dd878