name: selvbetjening-ui - Run cypress tests

on:
  push:
    branches:
      - test/cypress
    paths:
      - apps/selvbetjening-ui/**
      - '!apps/selvbetjening-ui/nais/redis-dev-gcp.yaml'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
#      - run: |
#         cd apps/selvbetjening-ui
#         pwd
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: apps/selvbetjening-ui
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
