name: selvbetjening-redis - Build, release and deploy

on:
  push:
    branches:
      - main
    paths:
      - apps/selvbetjening-ui/nais/redis.yaml

jobs:
  deploy-redis-dev-gcp:
    name: Deploy redis dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/selvbetjening-ui/nais/redis.yaml
