name: Slett alle caches
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Slett alle caches
        run: |
          gh extension install actions/gh-actions-cache
          gh cache delete --all
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}