name: Verify libs

on:
  push:
    paths:
      - libs/**

jobs:
  verify-branches:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16.x'

      # Build
      - name: Run Gradle Check
        run: |
          chmod +x ./gradlew
          ./gradlew check